<form action="" method="POST">
    <div class="form-group">
        <label for="login">Pseudo :</label>
        <input type="text" class="form-control" id="login" name="login">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe :</label>
        <input type="text" class="form-control" id="password" name="password">
    </div>
    <input type="submit" class="btn btn-primary" value="Se connecter">
</form>