<?php
    echo "<ul class='list-group'>";
        foreach($this->categs as $categ) {
                echo "<li class='list-group-item'>
                        <a href='categorie-update?id=$categ->id'>$categ->name</a>";
                        // if(isset($this->session->role) && $this->session->role == 2){
                            echo "<a onclick='return confirm(\" Etes vous sûr de vouloir supprimer cette catégorie ?\")' href='?iddelete=$categ->id' class='float-right'>
                                    <i class='fas fa-trash'></i>
                                </a>";
                        // }
                        echo "</li>";
        }
    echo "</ul>";
?>